[global]
# DataFrame serialization.
# Acceptable values:
#   - 'legacy': Serialize DataFrames using Streamlit's custom format. Slow but battle-tested.
#   - 'arrow': Serialize DataFrames using Apache Arrow. Much faster and versatile.
# Default: "arrow"
dataFrameSerialization = "legacy"

[browser]
# Whether to send usage statistics to Streamlit.
# Default: true
gatherUsageStats = false